-- The unified baseline already provisions issue_relations with the current
-- Parrot column names and constraints. Keep this historical migration as a
-- no-op; its former relation_type definition conflicted with that baseline.
