-- The unified baseline (00_init_schema_unified.sql) already provisions the
-- complete tool-access table family. Keep this historical migration as a
-- no-op so databases created from the baseline do not recreate those tables.
-- The original version duplicated baseline objects and could not be replayed
-- safely against an existing Parrot database.
