-- The unified baseline already provisions the Decision system schema.
-- This historical migration is intentionally a no-op: the original version
-- duplicated baseline objects and was not safe to replay on existing data.
